name: Build & Deploy
on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy .Net app
        uses: appleboy/ssh-action@v0.1.2
        with:
          host:  159.65.124.212 # IP address of the server you wish to ssh into
          key: ${{ secrets.PRIVATE_KEY }}    
          passphrase: gym13
          username: root # User of the server you want to ssh into
     
          script: |
            cd code
            cd Gym13
            git fetch origin
            git pull origin
            echo 'Deployment successful to digital ocean' 
